# Generated by Django 4.1.5 on 2023-01-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('text', models.TextField(blank=True)),
                ('price', models.PositiveIntegerField(help_text='Цена товара')),
                ('is_piblished', models.BooleanField(default=True)),
                ('time_creation', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
