# Generated by Django 4.1.5 on 2023-01-14 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='категория')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('text', models.TextField(blank=True)),
                ('price', models.PositiveIntegerField(help_text='Цена товара')),
                ('photo', models.ImageField(null=True, upload_to='photo')),
                ('is_piblished', models.BooleanField(default=True)),
                ('time_creation', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
            ],
        ),
    ]
